name: Update PR Description
on:
  pull_request_target:
    types:
      - opened

jobs:
  track_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Update PR Description
        run: |
          ORIGIN="https://${{ env.BRANCH }}--${{ env.REPO }}--${{ env.OWNER }}.aem.page"
          PREFIX=$(printf '%s\n' "$PREFIX" | sed -e 's/[\/&]/\\&/g')
          echo "PREFIX=${PREFIX}" >> $GITHUB_ENV
          PR_UPDATED_BODY="$(
            gh api /repos/$OWNER/$REPO/pulls/$PR_NUMBER | jq -r '.body' | \
            sed 's/{repo}/${{ env.REPO }}/g' | \
            sed 's/{branch}/${{ env.BRANCH }}/g' | \
            sed 's/{owner}/${{ env.OWNER }}/g' | \
            sed "s/\\$/$PREFIX/g"
          )"
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT_MOD_PERSONAL_TOKEN_CLASSIC }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          BRANCH: ${{ github.head_ref }}
          PR_NUMBER: ${{ github.event.number }}
